version: "3"
services:
  desafio_avanade_db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data1
    environment:
      POSTGRES_PASSWORD: user1
      POSTGRES_USER: user1
      POSTGRES_DB: desafio_avanade
    ports:
      - "5433:5432"

volumes:
  db-data:
    driver: local